danielschuster-muc/potter-db

.github/ISSUE_TEMPLATE/2_feature_request.yml

edit feature request

---

README.md

fix issue templates in readme

---

.github/ISSUE_TEMPLATE/2_feature_request.yml

- Replace *question* label with *enhancement*

edit labels on feature request template

---

frontend/src/lib/utils.js

See #177 
| Before | After |
|--------|-------|
|![image](https://user-images.githubusercontent.com/3858548/193472815-fb29960f-bc3d-43a3-a96b-15127e241197.png)|![image](https://user-images.githubusercontent.com/3858548/193472777-c02e1f80-a326-4b3a-8e7b-a044d55c36b3.png)|

Fix #177 Update default API URL

---

.github/ISSUE_TEMPLATE/2_feature_request.yml
.github/ISSUE_TEMPLATE/config.yml
.github/PULL_REQUEST_TEMPLATE.md
README.md

- Add 💬  emoij to discussion contact link 
- Edit readme
- Edit pr template
- Remove "good first issue" label on feature requests

edit readme and remove good first issue label on feature requests

---

README.md

- edit badges
- link open ideas

edit readme badges and add link to open ideas on discussions

---

ATTRIBUTION.md
frontend/src/components/pages/about/AboutContent.js

- add attribution file for images

Create attribution file

---

frontend/src/pages/404.js
frontend/src/pages/500.js

- create raw 500 page
- edit 404 page

add 500 page, edit 404 page

---

frontend/src/components/pages/characters/CharactersList.js
frontend/src/components/ui/SearchField.js
frontend/src/lib/load_characters.js
frontend/src/lib/load_data.js
frontend/src/pages/characters/index.js

refactor character search

---

backend/README.md
frontend/src/lib/utils.js

switch api domain to api.potterdb.com

---

frontend/src/components/ui/ListItemBox.js

- fix alignment of text and icon in character / movie list

fix alignment of text and icon in character / movie list

---

frontend/src/components/layout/Footer.js
frontend/src/components/pages/spells/SpellList.js
frontend/src/components/pages/spells/SpellListItem.js
frontend/src/components/pages/spells/[slug]/SpellDetails.js
frontend/src/components/pages/spells/[slug]/SpellMeta.js
frontend/src/lib/load_spells.js
frontend/src/lib/utils.js
frontend/src/pages/spells/[slug]/index.js
frontend/src/pages/spells/index.js

- Created pages for spell list and detailed spell information
- Created a load_spells.js for fetching spells data
- Add spells link to footer

feat: Spells page

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/pages/characters/CharacterList.js
frontend/src/components/pages/potions/PotionList.js
frontend/src/components/pages/spells/SpellList.js

As we don't have infinite scrolling anymore, the react-infinite-scroller package is no longer needed.

remove react infinite scroller

---

frontend/src/components/pages/index/SearchBar.js

add space between search and type

---

frontend/src/components/layout/Footer.js

fix footer: heading elements are not in sequential order

---

frontend/src/components/pages/index/SearchBar.js

Fixed responsive issues of search bar, button alignment and widths.

fix: responsive issue of search bar

---

frontend/src/components/pages/characters/[slug]/CharacterDetails.js
frontend/src/components/pages/movies/[slug]/MovieDetails.js
frontend/src/components/pages/potions/[slug]/PotionDetails.js
frontend/src/components/pages/spells/[slug]/SpellDetails.js

fix images in details pages

---

.github/workflows/rubyonrails.yml
backend/config/initializers/rack_attack.rb
backend/db/data/movies/fb_3.json
backend/db/migrate/20220913193346_create_movies.rb
backend/db/schema.rb
backend/spec/config/initializers/rack_attack_spec.rb

fix order in movies, change request limit, edit rack attack test

---

backend/app/controllers/graphql_controller.rb
backend/app/controllers/pages_controller.rb
backend/lib/rack/status_check.rb

Fix api responses

---

backend/app/graphql/types/book_type.rb
backend/app/graphql/types/movie_type.rb
backend/app/graphql/types/query_type.rb
backend/app/serializers/book_serializer.rb
backend/app/serializers/movie_serializer.rb
backend/db/data/books/1.json
backend/db/data/books/2.json
backend/db/data/books/3.json
backend/db/data/books/4.json
backend/db/data/books/5.json
backend/db/data/books/6.json
backend/db/data/books/7.json
backend/db/data/movies/fb_1.json
backend/db/data/movies/fb_2.json
backend/db/data/movies/fb_3.json
backend/db/migrate/20220908215540_create_books.rb
backend/db/schema.rb
backend/db/seeds.rb
backend/spec/factories/books.rb

- create graphql movie type
- add author to books
- fix some fields for movies

Create graphql movie type

---

frontend/src/components/pages/books/[slug]/BookDetails.js
frontend/src/pages/books/[slug]/index.js

fix loads only 20 chapters

---

frontend/src/components/pages/books/[slug]/BookDetails.js
frontend/src/components/ui/AccordionList.js
frontend/src/components/ui/CustomAccordion.js

fix accordion list for non-array values

---

.github/ISSUE_TEMPLATE/1_bug_report.yml
.github/ISSUE_TEMPLATE/2_feature_request.yml
.github/PULL_REQUEST_TEMPLATE.md
.github/dependabot.yml
CONTRIBUTING.md
README.md
docs/README.md

edit readme for docs as well as gh workflows etc.

---

frontend/src/components/layout/Footer.js

add docs to footer

---

frontend/src/components/Link.js
frontend/src/components/layout/Navbar.js
frontend/src/components/pages/books/BookListItem.js
frontend/src/components/pages/characters/CharacterListItem.js
frontend/src/components/pages/index/LandingPageBanner.js
frontend/src/components/pages/movies/MovieListItem.js
frontend/src/components/pages/potions/PotionListItem.js
frontend/src/components/pages/spells/SpellListItem.js
frontend/src/components/ui/DetailedInfoCard.js

With the switch to [next.js v13](https://nextjs.org/blog/next-13) images and links got broken. This issue is now solved by a tempory solution. We should switch to the new image / link components soon.

fix images and links in next v13

---

docs/next.config.mjs
docs/package-lock.json
docs/package.json
docs/pages/index.en.mdx
docs/public/sitemap-0.xml
docs/theme.config.tsx

update to nextra v2.0.0

---

backend/app/models/book.rb
backend/app/models/chapter.rb
backend/app/models/character.rb
backend/app/models/movie.rb
backend/app/models/potion.rb
backend/app/models/spell.rb
docs/theme.config.tsx
frontend/package-lock.json

fix ransack filtering not working, closes #585

---

docs/pages/_app.js
docs/theme.config.tsx

fix some minor things

---

.github/dependabot.yml

disable /frontend dependabot changes

---

.github/dependabot.yml

remove dependabot updates

---

frontend/package-lock.json

update frontend npm packages

---

.github/ISSUE_TEMPLATE/1_bug_report.yml
.github/ISSUE_TEMPLATE/2_feature_request.yml
.github/ISSUE_TEMPLATE/3_ticket.yml
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

Updates the issue and pull request templates.

update issue / pr templates

---

docs/lib/fetchers/graphqlFetcher.js
docs/lib/utils.js
docs/pages/apis/_meta.en.json
docs/pages/apis/graphql.en.mdx
docs/pages/apis/rest.en.mdx
docs/pages/getting-started.en.mdx
docs/pages/index.en.mdx
docs/pages/resources.en.mdx

- Add technical details table
- Improve layout of resources overview 
- Smaller improvements

add table for technical details, add cards for resources overview

---

README.md

Add Hacktoberfest 2023 Discussion link

Add Hacktoberfest 2023 Discussion link

---

docs/package-lock.json
docs/pages/apis/rest.en.mdx

https://github.com/danielschuster-muc/potter-db/discussions/745

improve pagination explaination

---

frontend/README.md

Update frontend Readme to inform about new-website branch.

Update frontend README.md

---

frontend/src/styles/globals.css

Added custom scrollbar in the new website.
Fixes #748

Feat: Added custom scrollbar

---

frontend/package-lock.json
frontend/package.json
frontend/src/app/layout.tsx
frontend/src/components/NProgressProvider.tsx

Working on adding in a progress bar. Currently there are issues with the component but have the majority of it in place.
Working to fix #750 
- [✅ ] This pull request has a meaningful title and description.
- [✅ ] I have read and followed the [Contributing guidelines](https://github.com/danielschuster-muc/potter-db/blob/master/CONTRIBUTING.md).
- [✅ ] My code follows the conventions and coding style of this project.

working on adding progress bar

---

docs/theme.config.tsx

Adds some translations on the docs:
- toc
- searchbar
- feedback
- edit links
- git timestamp
- themeswitch

Add translations for toc, searchbar, feedback, edit links etc.

---

frontend/next-sitemap.config.js
frontend/src/app/books/[slug]/layout.tsx
frontend/src/app/books/[slug]/loading.tsx
frontend/src/app/books/[slug]/page.tsx
frontend/src/app/books/layout.tsx
frontend/src/app/books/page.tsx
frontend/src/components/Footer.tsx
frontend/src/components/books/BookAccordionList.tsx
frontend/src/components/books/BookDetailsBody.tsx
frontend/src/components/books/BookDetailsBodyLeft.tsx
frontend/src/components/books/BookDetailsBodyRight.tsx
frontend/src/components/books/BookDetailsSkeleton.tsx
frontend/src/components/books/BookList.tsx
frontend/src/components/books/BookListItem.tsx
frontend/src/components/characters/CharacterAccordionList.tsx
frontend/src/components/characters/CharacterDetailsBodyRight.tsx
frontend/src/components/ui/TableRow.tsx
frontend/src/types/Book.ts
frontend/src/types/Chapters.ts
frontend/src/types/Character.ts

Creates book `index` and `show` pages.
#770

Create book pages

---

frontend/next.config.js

As we are reaching image optimization limits on vercel, this feature will be disabled for the old website.

Add unoptimized flag for images

---

docs/next.config.js
docs/pages/_meta.sk.json
docs/pages/apis/_meta.sk.json
docs/pages/apis/graphql.sk.mdx
docs/pages/apis/rest.sk.mdx
docs/pages/getting-started.sk.mdx
docs/pages/index.sk.mdx
docs/pages/resources.sk.mdx
docs/pages/resources/_meta.sk.json
docs/pages/resources/books.sk.mdx
docs/pages/resources/chapters.sk.mdx
docs/pages/resources/characters.sk.mdx
docs/pages/resources/movies.sk.mdx
docs/pages/resources/potions.sk.mdx
docs/pages/resources/spells.sk.mdx
docs/theme.config.tsx

Translation of the documentation into Slovak language.
Is part of #738

Add Slovak translations

---

frontend/src/app/layout.tsx
frontend/src/components/NavBarMenu.tsx
frontend/src/components/Navbar.tsx
frontend/src/components/navbar/Navbar.tsx
frontend/src/components/navbar/NavbarMenu.tsx

Created a nav bar as per the requirements in the ticket #775 
Fixes #775
If any changes are required please tell.

#775 create a better nav bar

---

frontend/src/app/layout.tsx
frontend/src/components/ui/ScrollToTopButton.tsx

Implemented a scroll to top button as per issue requirements. Positioned at the bottom right, it appears once the user scrolls down and smoothly takes them to the top when clicked. The icon comes from react-icons. Used React hooks to handle the button's visibility based on the page's scroll position. The button styling is done with Tailwind CSS to ensure it matches the website's color theme.
Changes:
1. Created ScrollToTopButton component.
2. Added ScrollToTopButton to the general layout component.
Testing:
Checked button visibility and functionality on various pages and on mobile.
Fixes #787 
***
***

Create ScrollToTop button

---

backend/db/data/books/1.json

I added first book summaries in 1.json file
#741

Add first book chapter summaries

---

frontend/next.config.js
frontend/src/app/about/page.tsx
frontend/src/components/Footer.tsx

Adds an about page with information about the project, it's story and a copyright disclaimer.

Add about page

---

frontend/package-lock.json
frontend/package.json
frontend/src/app/layout.tsx

Adds vercel analytics package.

Add vercel analytics

---

frontend/src/components/books/BookAccordionList.tsx

Change chapter overview to show summaries if available. 
Has summaries:
No summaries:

Improve book accordion list to show chapter summaries if available

---

frontend/src/app/page.tsx
frontend/src/components/HeroSection.tsx
frontend/src/components/InfoSection.tsx

Creates an section with some information about Potter DB, its API, Website and Data Source.

Info section

---

frontend/src/app/about/page.tsx
frontend/src/components/InfoSection.tsx
frontend/src/components/OverviewSection.tsx
frontend/src/components/navbar/NavbarMenu.tsx
frontend/src/components/ui/HoverLink.tsx
frontend/src/components/ui/LinkButton.tsx
frontend/src/components/ui/ScrollToTopButton.tsx
frontend/src/components/ui/SimpleLink.tsx

Multiple smaller changes regarding refactoring, spelling and styling.

Code cleanup n fixes

---

frontend/next.config.js
frontend/src/components/Footer.tsx
frontend/src/components/HeroSection.tsx
frontend/src/components/InfoSection.tsx
frontend/src/components/books/BookDetailsBodyLeft.tsx
frontend/src/components/books/BookListItem.tsx
frontend/src/components/movies/MovieDetailsBodyLeft.tsx
frontend/src/components/movies/MovieListItem.tsx
frontend/src/components/navbar/Navbar.tsx
frontend/src/components/navbar/NavbarMenu.tsx
frontend/src/components/ui/Accordion.tsx

Makes various improvements to SEO.

Improve SEO

---

frontend/next.config.js

Remove unoptimized Images Prop

---

README.md

Update of 2 broken links in README.md
Fixes #809

[ISSUE#809] readme - update broken links

---

frontend/package-lock.json
frontend/package.json
frontend/src/app/layout.tsx

Removes analytics from frontend website as they are not used.

Remove vercel analytics

---

backend/.rubocop.yml
backend/README.md
backend/docker-compose.yml

Decided to switch to docker only setup for rails. 
- x] My code follows the conventions and coding style of this project.

Switch to docker-only setup

---

backend/app/controllers/home_controller.rb
backend/config/routes.rb
backend/spec/config/initializers/rack_attack_spec.rb
backend/spec/controllers/application_spec.rb
backend/spec/requests/home_spec.rb

Add home route and fix some tests

---

frontend/next.config.js

Make images unoptimized
